"""
etl_load.py
-----------
Extract-Transform-Load step of the pipeline.

- Extracts raw_sales.csv (messy, generated by generate_data.py)
- Cleans it (nulls, text casing, whitespace, duplicates, invalid values)
- Loads the clean data into a SQLite database (sales.db) so it can be
  queried with SQL (see ../sql/analysis_queries.sql) and connected to
  directly from Power BI.

Run:
    python etl_load.py
"""

import sqlite3
import pandas as pd

RAW_PATH = "../data/raw_sales.csv"
DB_PATH = "../data/sales.db"
CLEAN_CSV_PATH = "../data/clean_sales.csv"


def extract(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    print(f"Extracted {len(df)} rows from {path}")
    return df


def transform(df: pd.DataFrame) -> pd.DataFrame:
    before = len(df)

    # 1. Remove exact duplicate rows
    df = df.drop_duplicates()

    # 2. Standardize text columns: trim whitespace, title case
    for col in ["region", "city", "category", "product", "payment_method", "customer_segment"]:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace("nan", pd.NA)
        if col in ["region", "city"]:
            df[col] = df[col].str.title()

    # 3. Fill missing categorical values with an explicit label
    #    (keeps rows usable in aggregations instead of dropping them)
    df["customer_segment"] = df["customer_segment"].fillna("Unknown")
    df["payment_method"] = df["payment_method"].fillna("Unknown")

    # 4. Drop rows with invalid quantities (data entry errors)
    df = df[df["quantity"] > 0]

    # 5. Parse dates and add useful derived columns
    df["order_date"] = pd.to_datetime(df["order_date"])
    df["order_year"] = df["order_date"].dt.year
    df["order_month"] = df["order_date"].dt.month
    df["order_month_name"] = df["order_date"].dt.strftime("%b")
    df["order_quarter"] = df["order_date"].dt.quarter

    # 6. Recompute net_sales defensively (guards against upstream errors)
    df["gross_sales"] = (df["unit_price"] * df["quantity"]).round(2)
    df["discount_amount"] = (df["gross_sales"] * df["discount_pct"] / 100).round(2)
    df["net_sales"] = (df["gross_sales"] - df["discount_amount"]).round(2)

    after = len(df)
    print(f"Transformed: {before} -> {after} rows "
          f"({before - after} removed as duplicates/invalid)")
    return df


def load(df: pd.DataFrame, db_path: str, csv_path: str) -> None:
    conn = sqlite3.connect(db_path)
    df.to_sql("sales", conn, if_exists="replace", index=False)
    conn.close()
    df.to_csv(csv_path, index=False)
    print(f"Loaded clean data -> {db_path} (table: sales) and {csv_path}")


if __name__ == "__main__":
    raw_df = extract(RAW_PATH)
    clean_df = transform(raw_df)
    load(clean_df, DB_PATH, CLEAN_CSV_PATH)
